cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.full.yml
pipeline/config/config.go
pipeline/config/config_test.go
pipeline/config/testdata/pipeline.full.yaml
test-deployment.yml
test-pipeline.yml

This corrects a design mistake assuming that deployments would only ever have one container inside of them, preventing you from injecting in different images for the other containers defined in the pod spec. Instead, you now define a imageDescription in your pipeline.yml and reference that throughout your stages to inject in the container image spec.

Split image descriptions

---

pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.optional.yml
pipeline/builder/types/types.go
test-deployment.yml

I found this undocumented portion of Spinnaker showing that config maps and secrets are optional by default. This makes troubleshooting difficult on new deployments if you don't have it set to false.
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/deploy/description/servergroup/DeployKubernetesAtomicOperationDescription.groovy#L241-L255
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/api/KubernetesApiConverter.groovy#L690-L693
Also, I didn't know what's the proper go-ism for creating a pointer to a bool. LMK if this setter is okay.

Making Configmaps/Secrets Optional

---

README.md

for some reason spinnaker throws a refid error if the pipeline json is not created with the linear flag

update readme with linear flag

---

pipeline/builder/types/types.go

Adds the application name to the `SpinnakerPipeline` type so we can post this to the Spinnaker API to update pipelines automatically.

Add Name and Application for Spinnaker pipeline types

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go

Defaulting RequisiteStageRefIds to an empty slice. Without it, the spinnaker ui encounters a js error and prevents the edit actions modal from loading.
There's probably a better way to test this where I don't have to load the manifest file in the test, but I'm not familiar enough with it yet.

Default RequisiteStageRefIds to empty slice

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go

This defaults `triggers` to an empty slice which will allow the Spinnaker UI's Edit Action to work when triggers aren't present in the pipeline.yml file.

Default Triggers to empty slice

---

pipeline/builder/types/types.go

if you have both keys showing then it doesn't use either.

SRE-5212 - secretKeyRefs are not working in Spinnaker

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/triggers.go
pipeline/builder/types/types.go
pipeline/config/config.go
test-pipeline.yml

This allows you to configure pipelines with Webhook triggers and parameters. This makes pipeline easier to kick off with HTTP requests instead of relying on Jenkins to finish builds. You can kick off any pipeline with parameters on a specific URL.

Add webhook & parameter support

---

pipeline/builder/kubernetes.go

Some manifest files are pretty big. This ups the buffer to be 1mb of space.

Support 1mb manifest files

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go
pipeline/config/config.go
test-pipeline.yml

Adding support for this scale manifest stage:
Spinnaker generated json looks like:
Looker deployments will want to use this because the current method is to deploy 1 pod, let migrations run, and then manually scale up to 5. There's no way to run Looker migrations as a one-off job at the moment due to Looker baking migrations in into their jar.

Add support for scale manifest stage

---

README.md
cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/builder/options.go
pipeline/builder/types/types.go
pipeline/config/config.go
pipeline/config/config_test.go
pipeline/config/testdata/pipeline.full.yaml

adding timeout overrides to the manual judgement stages (which are by default 72 hours)

SRESOLD-1090 - adding timeouts to spinnaker stages

---

cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/options.go
vendor/vendor.json

if you type `k8s-pipeline create test-pipeline --linear --override=int-k8s:ops` any stage that has `int-k8s` listed becomes `ops`.

Adding account override command line flag

---

pipeline/builder/builder.go

Turns out Estuary sets a basepath when generating pipelines that needs to be accounted for when reading in files

Support configurator files when run using a different basepath

---

pipeline/builder/builder.go

Support the new environment names added by estuary to override the old cluster
This allows us to use configurator files with the new environment names

Support new environment names

---

pipeline/builder/builder.go
pipeline/builder/types/triggers.go

By default:
Wait for the Jenkins build to complete before continuing
Don't fail the pipeline if the step fails
Also don't include the 'StageEnabled' in StageMetadata unless a condition is given

Fix default settings for Jenkins Build Steps

---

pipeline/builder/kubernetes.go
pipeline/builder/testdata/multiple-documents.yml

Pipeliner was exiting when it reached the first empty manifest. This PR will allow us to parse the file until the very end
```
...
---
---
apiVersion: apps/v1beta1
...
```

Support parsing empty manifests in embedded files

---

README.md

the last `deployEmbeddedManifests` example of the readme will generate the following unmarshall error:
```
cannot unmarshal !!str `manifes...` into config.ManifestFile
```
this PR fixes the yaml syntax to make the error go away.

update example yaml

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go
pipeline/config/config.go

Spinnaker allows you to override the default timeout of 30 minutes on deploy embedded manifest stages, but k8s-pipeliner does. So whenever a new commit comes in, the timeout gets reset to 30 minutes. This should give us the ability to specify overriding stage timeouts when we want to and keep them overridden.
I'm also adding the ability to actually specify an option list in your spinnaker parameters

PP-2369: Override StageTimeoutMs and Specify Options

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go
pipeline/config/config.go

After the Spinnaker upgrade, it seems that we're having issues with the default timeout values for various pipeline stages:
1. Pipelines that are kicked off by a parent Spinnaker pipeline stage, despite the parent being marked to wait for the child pipeline to complete, are being terminated by the parent stage.
1. Pipeline stages that apply embedded manifests and that do not specify an overriding timeout are being terminated before completing.
This PR sets the default timeout for kicking off child Spinnaker pipelines to 1 hour. This PR also sets the default timeout for deploying embedded manifests to 30 minutes -- this was the old behavior prior to upgrading Spinnaker.

PP-3113: override default timeouts; give spinnaker this ability too

---

README.md
pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go
pipeline/config/config.go

Add parsing for an evaluate variables stage in spinnaker
https://spinnaker.io/docs/guides/user/pipeline/expressions/#create-variables-using-an-evaluate-variables-stage
Allows evaluation of complex expressions that are stored in variables that can be reused throughout a pipeline. Can be referenced by the variable name plainly, e.g. 
```yaml
- name: EvaluateVariables
variables:
- key: ta
value: da
...
- name: some other stage
somefield: ${ ta }
```

PPP-3372 Add evaluate variables stage

---

cmd/k8s-pipeliner/main.go

workaround for https://github.com/namely/k8s-pipeliner/issues/77
This doesn't fix the problem. Even when `validate` is successful, it enters into the `err != nil`... changing the exit code to `255`.

workaround(validate): panic when trying to use inexistent .Error()

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/triggers.go
pipeline/builder/types/types.go

Spinnaker >= 1.30 validates the field `.trafficManagement` from `.stages[]`; If this field is missing, Spinnaker can not save the new pipeline (json file) and responds with `error: null`.
This PR adds the minimum structure of `.trafficManagement` to the built object.

SRE-8924: add TrafficManagement to stage metadata

---

README.md

Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
In Go 1.18, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will always act as if the -d flag were enabled.
https://go.dev/doc/go-get-install-deprecation

Deprecation of 'go get' for installing executables
