cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.full.yml
pipeline/builder/types/types.go
test-deployment.yml

Adds the ability to include volume sources for cluster definitions in spinnaker

Add volume source JSON targeting

---

cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/config/config.go
pipeline/config/config_test.go
pipeline/config/testdata/pipeline.full.yaml
test-pipeline.yml

This allows you to define multiple server groups for a deploy stage in `pipeline.yml` files.

Adds the ability to modify containers using overrides

---

cmd/k8s-pipeliner/main.go
pipeline/builder/builder.go
pipeline/builder/types/types.go
pipeline/config/config.go
test-pipeline.yml

Adds the option to add freeFormDetails to cluster groups via pipeline.yml

Add ability to add cluster details

---

cmd/k8s-pipeliner/main.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/config/config.go
test-pipeline.yml

The last PR got it most of the way there.

Fix dumb mistake where you couldnt actually select different images for containers

---

cmd/k8s-pipeliner/main.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.envfrom.yml
pipeline/builder/testdata/deployment.probes.yml
pipeline/builder/types/types.go
test-deployment.yml

* Adds `envFrom` fields on the container spec to Spinnaker JSON
* Adds `readinessProbe` from container spec to Spinnaker JSON

Add additional k8s container fields

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/types/types.go
pipeline/config/config.go
test-pipeline.yml

Add ability to add notifications to pipelines

---

pipeline/builder/builder.go
pipeline/builder/kubernetes.go
pipeline/builder/options.go
pipeline/builder/types/types.go

This allows this project to be used more as a library now too.

Add ability to have base paths for pipelining

---

pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/podspec.yml

Support PodSpecs as a source for pipeline config

---

cmd/k8s-pipeliner/main.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.envfrom.yml
pipeline/builder/types/types.go

Add secretRef support for envFrom

---

pipeline/builder/builder.go
pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.full.yml
pipeline/builder/testdata/deployment.initContainer.yml
pipeline/builder/types/types.go
test-deployment.yml
test-pipeline.yml

This re-uses the existing container logic to also handle `InitContainers`.

Add handler for init containers

---

pipeline/config/config.go

These fields don't need to be added to the JSON if they are empty.

Add omitempty to fields that dont need them

---

pipeline/builder/builder.go
pipeline/builder/types/types.go

This fixes a problem where job pods could not be annotated.

Add ability to annotate jobs

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/config/config.go

if the trigger doesn't exist in their pipeline.yml's set it to true.

Fixing Enabled Triggers

---

README.md
pipeline/config/config.go

These examples were super out of date, since this tool is more or less stable now in its API, I'm updating them.

Update README to include concrete examples

---

pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.fieldref.yml
pipeline/builder/types/types.go

Supports using fieldRefs in manifests for environment variables.

Add FieldRef to k8s-pipeliner

---

pipeline/builder/kubernetes.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.security.yml
pipeline/builder/types/types.go

Adds the ability to configure security context in spinnaker pipelines

Security context

---

README.md

Add some readme goodness about deploying k8s-configurator files

Update Readme with configuratorFiles info

---

README.md

So you can link people to specific sections

Add anchor links to README

---

.goreleaser.yml

Please refer: namely/homebrew-tap#4

Added custome_require for download strategy

---

examples/manifest-pipeline.yml
pipeline/builder/builder.go
pipeline/builder/types/types.go
pipeline/config/config.go
pipeline/config/config_test.go
pipeline/config/testdata/pipeline.full.yaml
vendor/vendor.json

Add webhook stage generation | PPP-476

---

vendor/vendor.json

Updates k8s-configurator to the revision after https://github.com/namely/k8s-configurator/pull/10 was merged in

Update k8s-configurator dependency to support annotations in configmaps

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/embedded_manifests_test.go
pipeline/builder/types/types.go
pipeline/config/config.go
test-pipeline.yml
vendor/vendor.json

Adds the option of triggering spinnaker pipelines as a step

Support triggering other pipelines as a step

---

.goreleaser.yml

Update goreleaser confiig as per https://goreleaser.com/deprecations/#brew

Update go releaser config

---

pipeline/builder/builder.go
pipeline/builder/builder_test.go
pipeline/builder/kubernetes_test.go
pipeline/builder/testdata/deployment.full.yml
test-pipeline.yml

- Fixes previous error by null checking
- Allows to override only memory or cpu
- Added tests

Allow individual resource overrides and check for null

---

.github/workflows/jira_comment.yml

**For PR Creator**:
- feat: create GitHub action "jira_comment" to comment on the Jira ticket once the PR is merged

SRE-8978: rollout jira_comment action

---

.github/workflows/jira_comment.yml

https://jira.namely.land/browse/SRE-9103

SRE-9103 ci: Add permissions to jira_comment workflow
